spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    initialize: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
      hostname: registry
      nonSecurePort: 8761