version: '2'
services:
  user-service:
    build: user-service
    restart: always
    ports:
      - 5000:5000
  sms-service:
    build: sms-service
    restart: always
    ports:
      - 3000:3000
  meeting-service:
    build: meeting-service
    restart: always
    ports:
      - 4000:4000


