version: '2'
services:
  PostgreSQL:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=test
      - DB_PASS=123
      - DB_NAME=test

    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql

  gateway-service:
      build: gateway-service
      restart: always
      ports:
       - 5000:5000

  eureka-service:
      build: eureka-service
      restart: always
      ports:
        - 8761:8761

  user-service:
        build: asuka
        restart: always
        ports:
          - 3000:3000

  sms-service:
          build: sms-service
          restart: always
          ports:
            - 3002:3002

  meeting-service:
            build: meeting-service
            restart: always
            ports:
              - 3003:3003


