server:
  port: 80

spring:
  application:
    name: gateway

zuul:
  routes:
    user-service:
      path: /api/v1/users/**
      url: http://ec2-18-191-213-25.us-east-2.compute.amazonaws.com:5000/api/v1/user
    sms-service:
      path: /api/v1/sms/**
      url: http://ec2-18-191-213-25.us-east-2.compute.amazonaws.com:3000/api/v1/sms
    meeting:
      path: /api/v1/meeting/**
      url: http://ec2-18-191-213-25.us-east-2.compute.amazonaws.com:4000/api/v1/meeting
    status:
      path: /api/v1/status/**
      url: http://ec2-18-191-213-25.us-east-2.compute.amazonaws.com:4000/api/v1/status