server:
  port: 5000

spring:
  application:
    name: gateway

zuul:
  routes:
    user-service:
      path: /api/v1/users/**
      url: http://user-service.us-east-2.elasticbeanstalk.com/api/v1/user
    sms-service:
      path: /api/v1/sms/**
      url: http://sms-service.us-east-2.elasticbeanstalk.com/api/v1/sms
    meeting:
      path: /api/v1/meeting/**
      url: http://meeting-service.us-east-2.elasticbeanstalk.com/api/v1/meeting
    meeting:
      path: /api/v1/meetingResponse/**
      url: http://meeting-service.us-east-2.elasticbeanstalk.com/api/v1/meetingResponse
    status:
      path: /api/v1/status/**
      url: http://meeting-service.us-east-2.elasticbeanstalk.com/api/v1/status

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry.us-east-2.elasticbeanstalk.com/eureka