server:
  port: 3003

spring:
  application:
    name: meeting-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://PostgreSQL:5432/bang
    username: test
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop