spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    initialize: true
    schema: classpath:scripts/*.sql
  jpa:
    hibernate:
          ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
      hostname: registry
      nonSecurePort: 8761